### ISSUE TITLE
Document changelog workflow

### ISSUE THREAD

**Issue by szechyjs** [chef/omnibus#506] opened 2015-06-29 20:43 UTC
I'm starting to use the changelog feature and I'm having difficulty figuring out the intended workflow.

If I'm getting ready to create a new release, let's say from 1.2.0 -> 1.3.0, what would be the process of generating manifests, changelogs, committing changes and tagging the repo?

From what I gather so far, the version-manifest.json is expected to be committed to the repo, else you must provide a copy with `--starting_manifest`. If this is the case, I feel like there is a chicken and the egg problem with adding the manifest to the repo. If I'm getting ready to release v1.3.0, I generate the manifests, commit, and tag as 1.3.0, the manifest will still say 1.2.0 since the 1.3.0 tag did not exist when the manifest was generated. If I generate and add the manifest after the tagging, then all builds will get a version number like 1.3.0-1-g1a2bc3e.

/cc @stevendanna

**Comment by stevendanna** [comment] 2015-07-06 10:37
@szechyjs Thanks for filing this issue.  

I think that there is going to be some tension between two different workflows.  One workflow in which users have a promotion pipeline where the binary artifact is the unit of promotion, and those that have one where the source repository is the unit of promotion.  The "build_git_revision" and "build_version" were added for our internal pipeline which is moving towards the later case, where the idea is that you might retroactively tag build_git_revision as a given version after promoting it (and where we set the version manually in the project config, not from the git tag).  In this world the version-manifests for the various releases live in our artifact repository, rather than the source code repository.  This is still a work in progress so a bit of what I've just described is aspirational.

However, I'd still like to support a mode where the unit of promotion is the source repository itself. Perhaps what we need is a command that would help you tag a release.  The command could:

1) Generate the manifest, but without a build_git_revision, setting the version to the desired NEXT_VERSION.  The build_git_revisions will be redundant information because we will be tagging the release.

2) Commit the manifest.

3) Tag the repsitory with NEXT_VERSION (perhaps even as an annotated tag with the changelog from LAST_VERSION to NEXT_VERSION as the content).

Thoughts?


What if we had a specific command for tagging a release that would commit the manifest with the version set to the desired version

**Comment by szechyjs** [comment] 2015-07-06 18:19
@stevendanna I think a command that does what you outlined above would greatly simplify my process of cutting a new release.

**Comment by lamont-granquist** [comment] 2019-11-19 21:10
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.

**Closed by lamont-granquist** 2019-11-19 21:10 UTC
